name: casdoor_flutter_example
description: An example Flutter app that signs in with Casdoor.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  casdoor_flutter_sdk: ^2.0.1
  cupertino_icons: ^1.0.8
  desktop_webview_window: ^0.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
